### ISSUE TITLE
Fix Lead Table Filter

### ISSUE THREAD

**Issue by r0ddy** [MiniCRM-Group/MiniCRM#31]
Right now, we are creating our own filter predicate function in [](https://github.com/MiniCRM-Group/MiniCRM/pull/29/files/93f8c5fda34a88872bbfde3e7bffb9a2d12e950c#diff-c4307d0f0f6a75fe72d30f84f4388541). Our method currently involves traversing each lead's JSON and appending all the values together in an accumulator and then checking if the filter string is a substring of this accumulator.

For example, consider a user filtering for "template" on this sample json:
```json
{
  "a": "temp", 
  "b": "late" 
}
```

Our filter predicate would include this in the filtered results because the filter string "template" is a substring of the concatenation of the values ("temp" + "late"). 

What we want to do instead is check if "template" is a substring of each value individually.

**Comment by ataddesse** [comment]
> Right now, we are creating our own filter predicate function in . Our method currently involves traversing each lead's JSON and appending all the values together in an accumulator and then checking if the filter string is a substring of this accumulator.
> 
> For example, consider a user filtering for "template" on this sample json:
> 
> ```json
> {
>   "a": "temp", 
>   "b": "late" 
> }
> ```
> 
> Our filter predicate would include this in the filtered results because the filter string "template" is a substring of the concatenation of the values ("temp" + "late").
> 
> What we want to do instead is check if "template" is a substring of each value individually.

The current filter field does not return anything if you try to combine two properties, such as name and phone number. Is that what you meant?

**Comment by r0ddy** [comment]
Adding this for more clarity:
![image](https://user-images.githubusercontent.com/66025811/87332450-94337800-c509-11ea-9cc8-427084db27e6.png)
